### ISSUE TITLE
BTRFS filesystem du support

### ISSUE THREAD

**Issue by vercas** [KSXGitHub/parallel-disk-usage#20]
An incredibly useful feature to have would be BTRFS-specific information, which shows how much of a file's contents are exclusive and how much is shared.  
The code of `btrfs filesystem du` is here: https://github.com/kdave/btrfs-progs/blob/master/cmds/filesystem-du.c  
This isn't going to be a trivial feature to add, but it's a feature that would really set this tool apart from alternatives.

**Comment by KSXGitHub** [comment]
Adding platform-specific/filesystem-specific features would turn this project into an unmaintainable mess, so I'm afraid that I must refuse. I am not going to accept pull requests either.

However, did you know that `parallel-disk-usage` can be used as a [library crate](https://docs.rs/parallel-disk-usage)? This means that, as long as you can construct a [`DataTree`](https://docs.rs/parallel-disk-usage/0.2.1/parallel_disk_usage/data_tree/struct.DataTree.html) from your BTRFS-specific code, you can use [`Visualizer`](https://docs.rs/parallel-disk-usage/0.2.1/parallel_disk_usage/visualizer/struct.Visualizer.html) to print a graph that looks just like that of `pdu`'s. I also plan to support importing/exporting JSON (https://github.com/KSXGitHub/parallel-disk-usage/issues/17, https://github.com/KSXGitHub/parallel-disk-usage/issues/18), when that happens, you can make your tool piping JSON to `pdu` to create visuals (It wouldn't be as fast as using the library crate directly however).

> This isn't going to be a trivial feature to add, but it's a feature that would really set this tool apart from alternatives.

Being known for something this tool doesn't do well is not better than not being known at all.

Anyway, if you still have questions, [open a discussion](https://github.com/KSXGitHub/parallel-disk-usage/discussions). If the structure of `DataTree` is insufficient to describe BTRFS directory tree, please let me know.
