### ISSUE TITLE
Example to use parallel-disk-usage as a crate.

### ISSUE THREAD

**Issue by tbellembois** [KSXGitHub/parallel-disk-usage#246]
Hi,

I would like to use parallel-disk-usage in one of my projet but I can't figure out how to use it.
Any example ?

Thanks

**Comment by KSXGitHub** [comment]
Are you looking to use `pdu` as a library crate for your own Rust project or its JSON API from the `pdu` program?

### As a crate

If you are trying to build a `pdu`-styled ASCII graph for your own data, see [`Visualizer`](https://docs.rs/parallel-disk-usage/0.9.0/parallel_disk_usage/visualizer/struct.Visualizer.html). You will need to supply it a `DataTree`.

If you are trying to create your own visualization for the data that is provided by `pdu`, see [`DataTree`](https://docs.rs/parallel-disk-usage/0.9.0/parallel_disk_usage/data_tree/struct.DataTree.html).

### As a program

There are `--json-input` and `--json-output` flags.

### The examples

The only examples are this repository in its entirety or whatever I provided on [docs.rs](https://docs.rs/parallel-disk-usage/0.9.0/parallel_disk_usage/).

**Comment by tbellembois** [comment]
`DataTree` is what I was looking for.

```rust
    let children = data_tree.children();
    let data = data_tree.data();

    debug!("data: {:?}", data);
    debug!("children: {:#?}", children);
```

Is there a way to limit the children depth?

Regards

**Comment by KSXGitHub** [comment]
> Is there a way to limit the children depth?

`Visualizer` has `max_depth`.

**Comment by tbellembois** [comment]
This works like a charm. Thanks !
