### ISSUE TITLE
[feature request]: A way to configure thread-count

### ISSUE THREAD

**Issue by Byron** [KSXGitHub/parallel-disk-usage#272]
Right now, `pdu` uses all available CPUs for disk traversal. This is fine on most filesystems on SSDs I suppose as they scale well.

Unfortunately that's not the case on APFS, where the best thread-count is 3 to 4 (even though I settled for 3). More threads make the operation slower, while burning just as much CPU, making it very inefficient.

`dua` sets the default amount of threads on MacOS specifically to 3 for that reason, and gets to run at optimal speed on MacOS at least.

Would be it possible to be able to set the amount of threads used by `pdu`? I love using `pdu` for getting an overview on what's using the most space, but found it got slower and slower with each `M` series improvement in cores, instead of faster.

Thank you.

**Comment by KSXGitHub** [comment]
Already implemented. You may benchmark `pdu --threads N` to see if it really works. If it doesn't, you may come back here create a new bug report.

**Comment by KSXGitHub** [comment]
(only implemented in the latest version)

**Comment by Byron** [comment]
Thanks a lot! 

That's a great point, it looks like I was on a local build and didn't get regular updates.

`--threads` does work as well, thank you!
