### ISSUE TITLE
Add pdu version to JSON

### ISSUE THREAD

**Issue by KSXGitHub** [KSXGitHub/parallel-disk-usage#28]

**Comment by Byron** [comment]
Maybe not the right ticket, apologies, but would it be possible to get a valid path for the traversal roots? Currently there would be no way to construct valid paths for deletion. For instance "dev" should be "/Users/byron/dev" as passed to `pdu`.

```
➜  dua-cli git:(main) pdu --version
pdu 0.4.0
➜  dua-cli git:(main) pdu --json-output   ~/dev | jq .
{
  "unit": "Bytes",
  "tree": {
    "name": "dev",
    "data": 99192443577,
    "children": [
      {
       
```

**Comment by KSXGitHub** [comment]
How about adding a `"root"` field to the top-level of the JSON?

**Comment by KSXGitHub** [comment]
Actually, forget about `"cwd"`, would https://github.com/KSXGitHub/parallel-disk-usage/issues/30 be sufficient?

**Comment by Byron** [comment]
Absolutely - anything that allows to construct a valid filesystem path. `cwd` should do and would probably be `/Users/byron` in the example above.

**Comment by KSXGitHub** [comment]
I just find a more elegant solution: Just display the root path as it was provided from the CLI (https://github.com/KSXGitHub/parallel-disk-usage/pull/31/commits/138319559a9f2dbb768c3d4221fd664638b149fc).

* `pdu` should display `.` as root.
* `pdu /Users/byron/dev` should display `/Users/byron/dev` as root (it was just `dev` before).
* `pdu $(pwd)` should display full path of current directory as root.

**Comment by KSXGitHub** [comment]
[v0.5.0](https://github.com/KSXGitHub/parallel-disk-usage/releases/tag/0.5.0) has been released.
