### ISSUE TITLE
Possible improvements?

### ISSUE THREAD

**Issue by farzadmf** [KSXGitHub/parallel-disk-usage#9]
Hello,

Thank you for the (super fast and) very useful utility. I can think of a couple of optional improvements:
- There could be a default pager when the output is more than one screen (similar to `bat`)
- Colors could be also a good nice option

But again, good job for the useful util :+1:

**Comment by KSXGitHub** [comment]
I would prefer that you divide this issue into 2, one for pager, and one for color.

**Comment by farzadmf** [comment]
I wasn't sure if you'll take them into consideration, but sure, I'll create two issues then :slightly_smiling_face: (and close this one)
